name: 'CI'

on:
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs_version: [23.4, 24.1, 24.2, 24.3, 24.4, 24.5, 25.1, 25.2, 25.3, 26.1, 26.2, 26.3, 27.1, 27.2, 28.1, 28.2, 29.1, 29.2, 29.3, 29.4, snapshot]
        exclude:
          - os: macos-latest
            emacs_version: 23.4
          - os: macos-latest
            emacs_version: 24.1
          - os: macos-latest
            emacs_version: 24.2
          - os: macos-latest
            emacs_version: 24.3
          - os: macos-latest
            emacs_version: 24.4
          - os: macos-latest
            emacs_version: 24.5
          - os: macos-latest
            emacs_version: 25.1
          - os: macos-latest
            emacs_version: 25.2
          - os: macos-latest
            emacs_version: 25.3
          - os: macos-latest
            emacs_version: 26.1
          - os: macos-latest
            emacs_version: 26.2
          - os: macos-latest
            emacs_version: 26.3
          - os: macos-latest
            emacs_version: 27.1
          - os: macos-latest
            emacs_version: 27.2

    steps:
    - uses: actions/checkout@v4

    - name: Setup Emacs
      uses: ./
      with:
        version: ${{ matrix.emacs_version }}

    - name: Check emacs version
      run: emacs --version
