name: 'CI'

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - '**.org'
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux-latest, macos-latest, windows-latest]
        emacs_version: [23.4, 24.1, 24.2, 24.3, 24.4, 24.5, 25.1, 25.2, 25.3, 26.1, 26.2, 26.3, 27.1, 27.2, 28.1, snapshot]

    steps:
    - uses: actions/checkout@v3

    - run: npm ci
    - run: npm run build

    - uses: ./
      with:
        version: ${{ matrix.emacs_version }}

    - name: Check emacs version
      run: emacs --version
